name: puzzle_adventure
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  path: ^1.8.0
  http: ^1.3.0 # Add this line (use the latest version available)
  flutter_dotenv: ^5.0.2 # Add this line (use the latest version available)

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  flutter_lints: ^5.0.0  # Add this line

flutter:
  uses-material-design: true

  assets:
    # Core assets
    - assets/
    - assets/logo.png
    - assets/background.jpg
    - assets/banner.png
    
    # Videos
    - assets/videos/video1.mp4
    - assets/videos/video2.mp4
    - assets/videos/video3.mp4
    
    # Puzzle images by flavor
    - assets/puzzle_images/
    - assets/puzzle_images/cartoons/imgs/
    - assets/puzzle_images/cartoons/puzzle/
    - assets/puzzle_images/pets/imgs/
    - assets/puzzle_images/pets/puzzle/
    - assets/puzzle_images/women/imgs/
    - assets/puzzle_images/women/puzzle/

    # other assets
    - .env
    
  fonts:
    - family: Petrona
      fonts:
        - asset: assets/fonts/Petrona-Bold.ttf
          weight: 700
        - asset: assets/fonts/Petrona-Regular.ttf
          weight: 400